language: python
python:
   - "3.4"
install: "pip install -r requirements.txt"
script:
   - make test_folders
   - coverage run --source=tammy run_tests.py
   - coverage report -m
   - make clean
after_success:
   coveralls --verbose
