language: python
python:
   - "3.4"
   - "3.5"
install: "pip install -r requirements.txt"
script:
   - coverage run --source=tammy `make test`
   - coverage report -m
after_success:
   coveralls --verbose
